### PR TITLE
Add .htaccess with short link redirects

### PR DESCRIPTION
**Pull request by sebschrader**
Replaces the ugly `linkCreator.sh` shell script that generates PHP files with redirects from Apache.

See #30 for details

### CODE REVIEW

**Comment by sebschrader** [comment]
Are these short links (`http://ese.ifsr.de/2016/<digit>`) even used anywhere @sjmielke? I couldn't find any clickable link.

They are only mentioned in the No Panic preface.

**Comment by kiliankoe** [comment]
All the links in the No Panic follow this template. They're mentioned in the preface and a reader is supposed to follow a link by entering `http://ese.ifsr.de/2016/<digit>` themselves.

**Comment by kiliankoe** [comment]
The good thing about the old script was that the redirects would be created automatically on building the no panic (afaik? - or could at least be run manually).
A good alternative would be to build this part of the .htaccess automatically as well.

**Comment by sebschrader** [comment]
I only know of `linkCreator.sh`, which is a shell script that creates PHP files. Maybe `linkCreator.sh` was created by another script. Then there would have been a script that generates another script that generates scripts.

I&#039;m not sure if I should let this keep going or try to put an end to this madness

**Comment by sjmielke** [comment]
So, what happened is this: I would comment out a couple lines in the tex file and then the generated file would contain unformatted number-link-pairs. I would put these in a file and then create a `echo`-line for each pair by running `sed` or something over the whole list. And this is how the `.sh` file comes into the world :) Yes, it's horrible.

**Comment by sjmielke** [comment]
Guess the best solution would be to make XeLaTeX write an `.htaccess` file on the side - I'm looking into that now :)

**Comment by sjmielke** [comment]
Compilation of the NoPanic now automatically generates a `kopimi.htaccess`. I'm surprised at how extremely easy it was and how clean the diff is!

**Comment by sebschrader** [comment]
We could compile the No Panic in the GitHub hook, but I'm not sure, if that's a good idea.

**Comment by sjmielke** [comment]
Jesus, this is a file that gets updated literally once a year :laughing:

**Comment by sebschrader** [comment]
No just because of the links. The No Panic PDF file needs to be uploaded as well.

But as I said, I'm not sure if it's a good idea. Probably not.

**Comment by sebschrader** [comment]
@sjmielke If you have the `kopime.htaccess` for the current year ready, please update the `.htaccess` in this PR. I guess many links changed due to the TUD Webrelaunch.

**Comment by sebschrader** [comment]
What's the status on this year's no panic links?

**Comment by sjmielke** [comment]
Done and ready to merge.

**Pull request merged**
